spring:
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  redis:
    host: localhost
    port: 6379
logging:
  config: classpath:log4j2.yml
